### ISSUE TITLE
Bedmap2 resampled on fetch crashes python

### ISSUE THREAD

**Issue by mdtanker** [mdtanker/antarctic_plots#119]
**Describe the bug**

When calling fetch bedmap2, python with crash on either the first, or subsequent calls to the same cell. This doesn't seem to happen with fetch bedmachine. Must be an issue with the fetch.resample_grd() and some issue with the bedmap2. 

**Full code that generate the error**

```python
region=regions.ross_ice_shelf
spacing=5e3
registration='g'
reference='geoid'

bedmap2 = fetch.bedmap2(
    layer='surface', 
    region=region,
    spacing=spacing,
    registration=registration,
    reference=reference,
    verbose='e',
    )
```
initial values for bedmap2:
```python
initial_region = [-3333500, 3333500, -3332500, 3332500]
initial_spacing = 1e3
initial_registration = "p"
```
For now have disabled resampled of bedmap2 and just return the loaded dataarray.

- [x] check which parameters have issues; region, spacing, registration, reference, or none ✔️ ALL
- [x] if issue with .tiff, preprocessing could convert to .nc files
- [x] check if issue with specific parameters used above.

**Comment by mdtanker** [comment]
Altered the fetch.bedmap2() functino to just return the tif file loaded as a dataarray.
```python
fname = [p for p in path if p.endswith(f"{layer}.tif")][0]
grid = xr.load_dataarray(fname).squeeze()
```
Then calling this
```python
grid = fetch.bedmap2(layer='surface')
grid
```
You can successfully call this as many times as you want without issues.

When you then try to resample that grid with pygmt.grdsample(), there is an issue.

```python
region=regions.ross_ice_shelf
spacing=5e3
registration='g'
reference='geoid'

bedmap2_surface = pygmt.grdsample(
    grid,
    spacing=spacing,
    region=region,
    registration=registration,
)
bedmap2_surface
```
```
grdsample [WARNING]: Output sampling interval in x exceeds input interval and may lead to aliasing.
grdsample [WARNING]: Output sampling interval in y exceeds input interval and may lead to aliasing.
Canceled future for execute_request message before replies were done
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
```
And the log

```
error 17:46:46.136: Disposing session as kernel process died ExitCode: 3221226356, Reason: c:\Users\matthewt\AppData\Local\miniforge3\envs\RIS_gravity_inversion_AP\lib\site-packages\traitlets\traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
c:\Users\matthewt\AppData\Local\miniforge3\envs\RIS_gravity_inversion_AP\lib\site-packages\traitlets\traitlets.py:2366: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '9cef07f1-18ad-415e-8700-e7444b61e580' instead of 'b"9cef07f1-18ad-415e-8700-e7444b61e580"'.
  warn(

info 17:46:46.136: Dispose Kernel process 15072.
error 17:46:46.136: Raw kernel process exited code: 3221226356
error 17:46:46.138: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (c:\Users\matthewt\.vscode\extensions\ms-toolsai.jupyter-2022.9.1202862440\out\extension.node.js:2:32353)
	at c:\Users\matthewt\.vscode\extensions\ms-toolsai.jupyter-2022.9.1202862440\out\extension.node.js:2:51405
	at Map.forEach (<anonymous>)
	at y._clearKernelState (c:\Users\matthewt\.vscode\extensions\ms-toolsai.jupyter-2022.9.1202862440\out\extension.node.js:2:51390)
	at y.dispose (c:\Users\matthewt\.vscode\extensions\ms-toolsai.jupyter-2022.9.1202862440\out\extension.node.js:2:44872)
	at c:\Users\matthewt\.vscode\extensions\ms-toolsai.jupyter-2022.9.1202862440\out\extension.node.js:2:2218254
	at t.swallowExceptions (c:\Users\matthewt\.vscode\extensions\ms-toolsai.jupyter-2022.9.1202862440\out\extension.node.js:7:130943)
	at p.dispose (c:\Users\matthewt\.vscode\extensions\ms-toolsai.jupyter-2022.9.1202862440\out\extension.node.js:2:2218232)
	at t.RawSession.dispose (c:\Users\matthewt\.vscode\extensions\ms-toolsai.jupyter-2022.9.1202862440\out\extension.node.js:2:2223340)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 17:46:46.138: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 17:46:46.140: Cancel all remaining cells true || Error || undefined
warn 17:46:46.150: 2022-11-03 17:46:46,140 UTC - WARNING - Unknown command: DISPOSE_INTERRUPT_HANDLE:22:20660
```

**Comment by mdtanker** [comment]
Same output occurs if you comment out `registration`, `region`, or `spacing`.

So even just calling pygmt.grdsample(grid) with no parameters crashes python.



Possibly unrelated, during import of the packages, continuously getting the following warning:
```
c:\Users\matthewt\AppData\Local\miniforge3\envs\RIS_gravity_inversion_AP\lib\site-packages\xarray\backends\cfgrib_.py:29: UserWarning: Failed to load cfgrib - most likely there is a problem accessing the ecCodes library. Try `import cfgrib` to get the full error message
  warnings.warn(
```

**Comment by mdtanker** [comment]
Okay making some progress. Loading the .tif file, saving it to a .nc, and reloading that seems to fix the issue!

Seems to work with multiple calls to either pygmt.grdsample(), or to the function fetch.resample_grd(), both which failed before. This must mean its a pygmt / GMT issue with .tif files, since I haven't seen this issue with any of the other .nc files I resample in exactly the same way. 

Now I need to re-organize the fetch.bedmap2 call to preprocess each layer into a .nc file, and return the loaded/resampled dataarray.
